import os
import sqlite3
import bcrypt
import csv

# Check if DATABASE_URL is set (Render/Supabase mode) or local SQLite mode
DATABASE_URL = os.getenv("DATABASE_URL")

def get_db():
    """Returns a database connection depending on whether DATABASE_URL is present."""
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row
        # Connect to Supabase PostgreSQL
        conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        return conn
    else:
        # Connect to local SQLite database
        conn = sqlite3.connect("hardware_inventory.db")
        conn.row_factory = sqlite3.Row
        return conn

def init_db():
    """Initializes tables if they don't exist."""
    conn = get_db()
    cur = conn.cursor()
    
    if DATABASE_URL:
        # PostgreSQL Table Definitions
        cur.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                email TEXT NOT NULL DEFAULT 'user@campus.edu',
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')),
                failed_attempts INTEGER NOT NULL DEFAULT 0,
                is_locked INTEGER NOT NULL DEFAULT 0
            );
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS password_resets (
                request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL,
                email TEXT NOT NULL,
                new_password_hash TEXT NOT NULL,
                request_time TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
            );
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS hardware (
                item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                item_name TEXT NOT NULL,
                category TEXT NOT NULL,
                quantity INTEGER NOT NULL,
                unit_price DOUBLE PRECISION NOT NULL,
                status TEXT NOT NULL
            );
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS loans (
                loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL,
                item_id BIGINT NOT NULL,
                item_name TEXT NOT NULL,
                borrow_date TEXT NOT NULL,
                return_date TEXT,
                quantity INTEGER NOT NULL DEFAULT 1,
                status TEXT NOT NULL DEFAULT 'PENDING_BORROW' CHECK (status IN ('PENDING_BORROW', 'BORROWED', 'RETURN_PENDING', 'RETURNED'))
            );
        """)
    else:
        # SQLite Table Definitions
        cur.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                email TEXT NOT NULL DEFAULT 'user@campus.edu',
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'USER',
                failed_attempts INTEGER NOT NULL DEFAULT 0,
                is_locked INTEGER NOT NULL DEFAULT 0
            );
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS password_resets (
                request_id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL,
                email TEXT NOT NULL,
                new_password_hash TEXT NOT NULL,
                request_time TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'PENDING'
            );
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS hardware (
                item_id INTEGER PRIMARY KEY AUTOINCREMENT,
                item_name TEXT NOT NULL,
                category TEXT NOT NULL,
                quantity INTEGER NOT NULL,
                unit_price REAL NOT NULL,
                status TEXT NOT NULL
            );
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS loans (
                loan_id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL,
                item_id INTEGER NOT NULL,
                item_name TEXT NOT NULL,
                borrow_date TEXT NOT NULL,
                return_date TEXT,
                quantity INTEGER NOT NULL DEFAULT 1,
                status TEXT NOT NULL DEFAULT 'PENDING_BORROW'
            );
        """)
    
    conn.commit()
    conn.close()

def query_db(query, args=(), one=False):
    """Helper to execute queries and automatically handle parameter placeholders (? vs %s)."""
    conn = get_db()
    cur = conn.cursor()
    
    if DATABASE_URL:
        query = query.replace("?", "%s")
        
    cur.execute(query, args)
    
    if DATABASE_URL:
        try:
            rv = cur.fetchall()
        except Exception:
            rv = None
    else:
        rv = cur.fetchall()
        
    conn.commit()
    conn.close()
    return (rv[0] if rv else None) if one else rv

def execute_db(query, args=()):
    """Helper to execute write/update/delete operations."""
    conn = get_db()
    cur = conn.cursor()
    if DATABASE_URL:
        query = query.replace("?", "%s")
    cur.execute(query, args)
    conn.commit()
    conn.close()


class AuthController:
    @staticmethod
    def register_user(username, email, password, role="USER"):
        if not username or not password:
            return False, "Username and password are required."
        
        existing = query_db("SELECT * FROM users WHERE username = ?", (username,), one=True)
        if existing:
            return False, "Username already exists."
        
        hashed = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
        try:
            execute_db(
                "INSERT INTO users (username, email, password_hash, role) VALUES (?, ?, ?, ?)",
                (username, email or "user@campus.edu", hashed, role)
            )
            return True, "Account registered successfully! You can now log in."
        except Exception as e:
            return False, f"Registration failed: {str(e)}"

    @staticmethod
    def login_user(username, password):
        user = query_db("SELECT * FROM users WHERE username = ?", (username,), one=True)
        if not user:
            return False, "Invalid username or password.", "USER", 0, ""
        
        if user["is_locked"]:
            return False, "Account is locked due to failed login attempts.", "USER", 1, user["email"]
        
        if bcrypt.checkpw(password.encode('utf-8'), user["password_hash"].encode('utf-8')):
            execute_db("UPDATE users SET failed_attempts = 0 WHERE username = ?", (username,))
            return True, "Login successful!", user["role"], 0, user["email"]
        else:
            attempts = user["failed_attempts"] + 1
            locked = 1 if attempts >= 3 else 0
            execute_db("UPDATE users SET failed_attempts = ?, is_locked = ? WHERE username = ?", (attempts, locked, username))
            if locked:
                return False, "Account locked due to 3 consecutive failed login attempts.", "USER", 1, user["email"]
            return False, f"Invalid password. Attempt {attempts} of 3.", "USER", 0, user["email"]

    @staticmethod
    def submit_password_reset_request(username, email, new_password):
        user = query_db("SELECT * FROM users WHERE username = ? AND email = ?", (username, email), one=True)
        if not user:
            return False, "Username and email do not match our records."
        
        hashed = bcrypt.hashpw(new_password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
        import datetime
        time_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        execute_db(
            "INSERT INTO password_resets (username, email, new_password_hash, request_time, status) VALUES (?, ?, ?, ?, 'PENDING')",
            (username, email, hashed, time_str)
        )
        return True, "Password reset/unlock request submitted to administrator."

    @staticmethod
    def change_password_direct(username, email, old_password, new_password):
        user = query_db("SELECT * FROM users WHERE username = ?", (username,), one=True)
        if not user or not bcrypt.checkpw(old_password.encode('utf-8'), user["password_hash"].encode('utf-8')):
            return False, "Incorrect old password."
        
        hashed = bcrypt.hashpw(new_password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
        execute_db("UPDATE users SET password_hash = ? WHERE username = ?", (hashed, username))
        return True, "Password updated successfully."

    @staticmethod
    def get_pending_resets():
        return query_db("SELECT * FROM password_resets WHERE status = 'PENDING'")

    @staticmethod
    def process_bulk_resets(request_ids, approve, new_password_if_any, admin_id):
        for req_id in request_ids:
            req = query_db("SELECT * FROM password_resets WHERE request_id = ?", (req_id,), one=True)
            if not req:
                continue
            if approve:
                execute_db("UPDATE users SET password_hash = ?, is_locked = 0, failed_attempts = 0 WHERE username = ?", (req["new_password_hash"], req["username"]))
                execute_db("UPDATE password_resets SET status = 'APPROVED' WHERE request_id = ?", (req_id,))
            else:
                execute_db("UPDATE password_resets SET status = 'REJECTED' WHERE request_id = ?", (req_id,))
        return True, "Password reset requests processed successfully."


class InventoryController:
    @staticmethod
    def _ensure_loans():
        pass

    @staticmethod
    def get_all_items(search="", category="ALL"):
        if category and category != "ALL":
            if search:
                return query_db("SELECT * FROM hardware WHERE category = ? AND (item_name LIKE ? OR category LIKE ?)", (category, f"%{search}%", f"%{search}%"))
            return query_db("SELECT * FROM hardware WHERE category = ?", (category,))
        else:
            if search:
                return query_db("SELECT * FROM hardware WHERE item_name LIKE ? OR category LIKE ?", (f"%{search}%", f"%{search}%"))
            return query_db("SELECT * FROM hardware")

    @staticmethod
    def get_categories():
        rows = query_db("SELECT DISTINCT category FROM hardware")
        return [row["category"] for row in rows]

    @staticmethod
    def get_user_active_loans(username):
        return query_db("SELECT * FROM loans WHERE username = ? AND status = 'BORROWED'", (username,))

    @staticmethod
    def get_user_pending_borrows(username):
        return query_db("SELECT * FROM loans WHERE username = ? AND status = 'PENDING_BORROW'", (username,))

    @staticmethod
    def get_user_loan_history(username):
        return query_db("SELECT * FROM loans WHERE username = ? AND status IN ('RETURNED', 'RETURN_PENDING')", (username,))

    @staticmethod
    def get_pending_returns():
        return query_db("SELECT * FROM loans WHERE status = 'RETURN_PENDING'")

    @staticmethod
    def get_pending_borrows():
        return query_db("SELECT * FROM loans WHERE status = 'PENDING_BORROW'")

    @staticmethod
    def get_all_loans_history():
        return query_db("SELECT * FROM loans")

    @staticmethod
    def borrow_item(username, item_id, quantity=1):
        item = query_db("SELECT * FROM hardware WHERE item_id = ?", (item_id,), one=True)
        if not item:
            return False, "Hardware item not found."
        if item["quantity"] < quantity:
            return False, f"Not enough stock available. Only {item['quantity']} left."
        
        import datetime
        date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        execute_db(
            "INSERT INTO loans (username, item_id, item_name, borrow_date, quantity, status) VALUES (?, ?, ?, ?, ?, 'PENDING_BORROW')",
            (username, item_id, item["item_name"], date_str, quantity)
        )
        return True, "Borrow request submitted successfully."

    @staticmethod
    def request_bulk_item_returns(loan_ids):
        for lid in loan_ids:
            execute_db("UPDATE loans SET status = 'RETURN_PENDING' WHERE loan_id = ? AND status = 'BORROWED'", (lid,))
        return True, "Return requests submitted for approval."

    @staticmethod
    def add_item(item_name, category, quantity, unit_price):
        status = "AVAILABLE" if quantity > 0 else "OUT OF STOCK"
        execute_db(
            "INSERT INTO hardware (item_name, category, quantity, unit_price, status) VALUES (?, ?, ?, ?, ?)",
            (item_name, category, quantity, unit_price, status)
        )
        return True, "Hardware item added successfully."

    @staticmethod
    def delete_bulk_items(item_ids):
        for iid in item_ids:
            execute_db("DELETE FROM hardware WHERE item_id = ?", (iid,))
        return True, "Selected items deleted successfully."

    @staticmethod
    def process_bulk_borrows(loan_ids, approve):
        for lid in loan_ids:
            loan = query_db("SELECT * FROM loans WHERE loan_id = ?", (lid,), one=True)
            if not loan:
                continue
            if approve:
                item = query_db("SELECT * FROM hardware WHERE item_id = ?", (loan["item_id"],), one=True)
                if item and item["quantity"] >= loan["quantity"]:
                    new_qty = item["quantity"] - loan["quantity"]
                    new_status = "AVAILABLE" if new_qty > 0 else "OUT OF STOCK"
                    execute_db("UPDATE hardware SET quantity = ?, status = ? WHERE item_id = ?", (new_qty, new_status, loan["item_id"]))
                    execute_db("UPDATE loans SET status = 'BORROWED' WHERE loan_id = ?", (lid,))
                else:
                    execute_db("UPDATE loans SET status = 'REJECTED' WHERE loan_id = ?", (lid,))
            else:
                execute_db("UPDATE loans SET status = 'REJECTED' WHERE loan_id = ?", (lid,))
        return True, "Borrow requests processed."

    @staticmethod
    def process_bulk_returns(loan_ids, approve):
        for lid in loan_ids:
            loan = query_db("SELECT * FROM loans WHERE loan_id = ?", (lid,), one=True)
            if not loan:
                continue
            if approve:
                item = query_db("SELECT * FROM hardware WHERE item_id = ?", (loan["item_id"],), one=True)
                if item:
                    new_qty = item["quantity"] + loan["quantity"]
                    execute_db("UPDATE hardware SET quantity = ?, status = 'AVAILABLE' WHERE item_id = ?", (new_qty, loan["item_id"]))
                import datetime
                ret_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                execute_db("UPDATE loans SET status = 'RETURNED', return_date = ? WHERE loan_id = ?", (ret_date, lid))
            else:
                execute_db("UPDATE loans SET status = 'BORROWED' WHERE loan_id = ?", (lid,))
        return True, "Return requests processed."

    @staticmethod
    def export_to_csv(username):
        items = query_db("SELECT * FROM hardware")
        filename = "inventory_report.csv"
        try:
            with open(filename, mode="w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow(["Item ID", "Item Name", "Category", "Quantity", "Unit Price", "Status"])
                for item in items:
                    writer.writerow([item["item_id"], item["item_name"], item["category"], item["quantity"], item["unit_price"], item["status"]])
            return True, "Export successful."
        except Exception as e:
            return False, str(e)