import os  # Provides access to operating-system environment variables.
import sqlite3  # Provides SQLite database access for the original local database.
import psycopg  # Provides PostgreSQL database access.
from psycopg import sql  # Provides safe SQL construction for table and column identifiers.

SQLITE_DB = "hardware_inventory.db"  # Stores the filename of the original SQLite database.
DATABASE_URL = os.getenv("DATABASE_URL")  # Reads the PostgreSQL connection string from the environment.

if not DATABASE_URL:  # Checks whether the PostgreSQL connection string was provided.
    raise RuntimeError("DATABASE_URL is not set.")  # Stops the migration if the connection string is missing.

sqlite_conn = sqlite3.connect(SQLITE_DB)  # Opens the original SQLite database.
sqlite_conn.row_factory = sqlite3.Row  # Allows SQLite rows to be accessed by column name.
pg_conn = psycopg.connect(DATABASE_URL)  # Opens a connection to the Supabase PostgreSQL database.
pg_conn.autocommit = False  # Uses a transaction so changes can be rolled back if an error occurs.

try:  # Starts the protected migration section.
    pg_cur = pg_conn.cursor()  # Creates a PostgreSQL cursor for SQL commands.
    sqlite_cur = sqlite_conn.cursor()  # Creates a SQLite cursor for reading source data.

    # PostgreSQL table definitions mapped precisely from your local SQLite schema
    table_definitions = {
        "users": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT UNIQUE NOT NULL",
            "email TEXT UNIQUE NOT NULL",
            "password_hash TEXT NOT NULL",
            "role TEXT NOT NULL DEFAULT 'USER'",
            "is_locked INTEGER NOT NULL DEFAULT 0",
            "failed_attempts INTEGER NOT NULL DEFAULT 0",
            "created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP",
        ],
        "reset_requests": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "user_id BIGINT NOT NULL",
            "email TEXT NOT NULL",
            "status TEXT NOT NULL DEFAULT 'PENDING'",
            "requested_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "reviewed_at TEXT",
            "reviewed_by BIGINT",
            "FOREIGN KEY(user_id) REFERENCES users(id)",
            "FOREIGN KEY(reviewed_by) REFERENCES users(id)",
        ],
        "hardware": [
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_name TEXT NOT NULL",
            "category TEXT NOT NULL",
            "quantity INTEGER NOT NULL",
            "unit_price REAL NOT NULL",
            "status TEXT NOT NULL",
            "created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP",
        ],
    }

    for table_name, columns in table_definitions.items():  # Processes each required application table.
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)  # Safely combines column definitions.
        create_sql = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(sql.Identifier(table_name), column_sql)  # Builds the CREATE TABLE statement.
        pg_cur.execute(create_sql)  # Creates the table if it does not already exist.

    counts = {}  # Creates a dictionary for recording migrated row counts.

    for table_name, columns in table_definitions.items():  # Processes each table for data migration.
        pg_cur.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name)))  # Checks whether the destination table already has data.
        destination_count = pg_cur.fetchone()[0]  # Reads the number of existing rows.

        if destination_count > 0:  # Checks whether the destination table is already populated.
            raise RuntimeError(f"Destination table '{table_name}' is not empty.")  # Stops to prevent accidental duplicate migration.

        # Fixed: Using a standard string query for SQLite since SQLite doesn't use psycopg.sql
        sqlite_cur.execute(f"SELECT * FROM {table_name}")  # Reads all rows from the matching SQLite table.
        rows = sqlite_cur.fetchall()  # Stores the source rows in memory.
        counts[table_name] = len(rows)  # Records how many rows will be migrated.

        if not rows:  # Checks whether the source table has no rows.
            continue  # Moves to the next table when there is nothing to copy.

        source_columns = [description[0] for description in sqlite_cur.description]  # Gets the SQLite column names.
        insert_columns = source_columns[:]  # Makes a copy of the source column list for the INSERT statement.

        column_identifiers = sql.SQL(", ").join(sql.Identifier(column) for column in insert_columns)  # Safely builds the INSERT column list.
        placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in insert_columns)  # Creates one PostgreSQL placeholder per value.
        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(sql.Identifier(table_name), column_identifiers, placeholders)  # Builds the INSERT statement.

        for row in rows:  # Processes every source row.
            values = [row[column] for column in source_columns]  # Gets the source values in column order.
            pg_cur.execute(insert_sql, values)  # Inserts the current row into PostgreSQL.

    sequence_columns = {  # Maps each table to its identity ID column.
        "users": "id",
        "reset_requests": "id",
        "hardware": "item_id",
    }  # Ends the identity column mapping.

    for table_name, id_column in sequence_columns.items():  # Processes each identity column.
        sequence_sql = sql.SQL("SELECT setval(pg_get_serial_sequence({}, {}), COALESCE(MAX({}), 0), MAX({}) IS NOT NULL) FROM {}").format(  # Builds SQL to synchronize the identity sequence with the migrated IDs.
            sql.Literal(table_name),
            sql.Literal(id_column),
            sql.Identifier(id_column),
            sql.Identifier(id_column),
            sql.Identifier(table_name),
        )
        pg_cur.execute(sequence_sql)  # Updates the identity sequence after explicit IDs were inserted.

    pg_conn.commit()  # Permanently saves all migrated tables and rows.
    print("Migration completed successfully.")  # Reports that the migration finished.
    for table_name, count in counts.items():
        print(f"  {table_name}: {count}")

except Exception:  # Catches any error during migration.
    pg_conn.rollback()  # Cancels PostgreSQL changes made during the failed transaction.
    raise  # Re-raises the original error so the student can see the problem.

finally:  # Runs cleanup whether migration succeeds or fails.
    sqlite_conn.close()  # Closes the SQLite database connection.
    pg_conn.close()  # Closes the PostgreSQL database connection.